Add file RestaurantListItemTableViewCell
devpass-tech/challenge-viewcode-delivery pull request #21
Opened 2022-04-07 08:42 UTC by thyagoraphael

### Descrição e Solução
- Created RestaurantListItemTableViewCell file made in class.
 
### Checklist:
- [ ] Não adiciona código duplicado
- [ ] Não contém código comentado
- [ ] Não contém código WIP
- [ ] Teste Unitário Implementado
 
### Evidências:
| iPhone SE | iPhone 13 Pro Max |
| ------ | ------ |
| print  | print |

2022-04-07 14:05 UTC, rafsouzap requested changes
Muito bom @thyagoraphael. Só senti falta do arquivo referente ao teste de snapshot. Você consegue inclui-lo neste PR?

2022-04-07 14:05 UTC, rafsouzap commented on solutions/devsprint-rafael-de-paula-1/DeliveryApp/Screens/Components/RestaurantListView/RestaurantListItemTableViewCell.swift
> +        label.backgroundColor = .magenta
@thyagoraphael alguns pontos:
* considere não inicializar esta label com o texto já definido, a função `configure` será a responsável por essa atribuição
* como o layout não possui uma cor de funda, considere remover o `backgroundColor`

2022-04-07 14:05 UTC, rafsouzap commented on solutions/devsprint-rafael-de-paula-1/DeliveryApp/Screens/Components/RestaurantListView/RestaurantListItemTableViewCell.swift
> +        label.text = "Lorem ipsum dolor"
@thyagoraphael alguns pontos:
* considere não inicializar esta label com o texto já definido, a função `configure` será a responsável por essa atribuição
* como o layout não possui uma cor de funda, considere remover o `backgroundColor`

2022-04-07 19:12 UTC, thyagoraphael commented on solutions/devsprint-rafael-de-paula-1/DeliveryApp/Screens/Components/RestaurantListView/RestaurantListItemTableViewCell.swift
> +        label.backgroundColor = .magenta
Removido os pontos citados e adicionando o teste de snapshot.

2022-04-07 19:12 UTC, thyagoraphael commented on solutions/devsprint-rafael-de-paula-1/DeliveryApp/Screens/Components/RestaurantListView/RestaurantListItemTableViewCell.swift
> +        label.text = "Lorem ipsum dolor"
Removido os pontos citados e adicionando o teste de snapshot.

2022-04-08 00:40 UTC, rafsouzap approved these changes

2022-04-08 00:41 UTC, merged